
/** @file
 *  @brief Bluetooth Mesh Configuration Data.
 */

/*
 * Copyright (c) 2017 Intel Corporation
 *
 * SPDX-License-Identifier: Apache-2.0
 */

#ifndef __BT_MESH_CONFIG_H
#define __BT_MESH_CONFIG_H

#define CONFIG_BT_MESH_NODE_ID_TIMEOUT 60
#define CONFIG_BT_MESH_PROXY_FILTER_SIZE 1
#define CONFIG_BT_MESH_SUBNET_COUNT 1
#define CONFIG_BT_MESH_APP_KEY_COUNT 1
#define CONFIG_BT_MESH_MODEL_KEY_COUNT 1
#define CONFIG_BT_MESH_MODEL_GROUP_COUNT 1
#define CONFIG_BT_MESH_LABEL_COUNT 1
#define CONFIG_BT_MESH_CRPL 10
#define CONFIG_BT_MESH_MSG_CACHE_SIZE 10
#define CONFIG_BT_MESH_ADV_BUF_COUNT 20
#define CONFIG_BT_MESH_TX_SEG_MSG_COUNT 6
#define CONFIG_BT_MESH_RX_SEG_MSG_COUNT 1
#define CONFIG_BT_MESH_RX_SDU_MAX 384
#define CONFIG_BT_ACL_CONNECTIONS 2
#define CONFIG_BT_MESH_PBA_SAME_TIME 10
#define CONFIG_BT_MESH_PBG_SAME_TIME 1
#endif /* __BT_MESH_CONFIG_H */
